apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana.yaml
  - grafana-dashboards.yaml
  - minio.yaml
  - nats.yaml
  - postgres.yaml
  - prometheus.yaml

configMapGenerator:
  - name: postgres-init
    files:
      - init.sql=postgres-init.sql
    options:
      disableNameSuffixHash: true
