apiVersion: v1
kind: ConfigMap
metadata:
  name: ledgerflux-ingestor-config
  namespace: ledgerflux
data:
  config.json: |
    {
      "products": ["BTC-USD", "ETH-USD", "ADA-USD"],
      "channels": ["ticker", "heartbeat"],
      "ws_uri": "wss://ws-feed.exchange.coinbase.com",
      "num_shards": 4,
      "stream_name": "market_ticks",
      "subject_prefix": "market.ticks"
    }
